FROM debian:sid-slim

LABEL maintainer=<nic.cheneweth@thoughtworks.com>

# minimum packages required for use as a circleci remote-docker primary container
# hadolint ignore=DL3008
RUN apt-get update && \
    apt-get install --no-install-recommends -y \
            git \
            openssh-server \
            tar \
            gzip \
            ca-certificates && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
