FROM debian:sid-20220801-slim

LABEL maintainer=<nic.cheneweth@thoughtworks.com>

# minimum packages required for use as a circleci remote-docker primary container
RUN apt-get update && \
    apt-get install --no-install-recommends -y \
            git=1:2.37.2-1 \ 
            openssh-server=1:9.0p1-1+b1 \
            tar=1.34+dfsg-1 \
            gzip=1.12-1 \
            ca-certificates=20211016 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
