FROM debian:sid-20230227-slim

LABEL org.opencontainers.image.title="circleci-remote-docker" \
      org.opencontainers.image.description="Debian-based CircleCI executor image containing only the minimum required packages" \
      org.opencontainers.image.documentation="https://github.com/ThoughtWorks-DPS/circleci-remote-docker" \
      org.opencontainers.image.source="https://github.com/ThoughtWorks-DPS/circleci-remote-docker" \
      org.opencontainers.image.url="https://github.com/ThoughtWorks-DPS/circleci-remote-docker" \
      org.opencontainers.image.vendor="ThoughtWorks, Inc." \
      org.opencontainers.image.authors="nic.cheneweth@thoughtworks.com" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.created="CREATED" \
      org.opencontainers.image.version="VERSION"

RUN apt-get update && \
    apt-get install --no-install-recommends -y \
            git=1:2.40.0-1 \
            openssh-server=1:9.2p1-2 \
            tar=1.34+dfsg-1.1 \
            gzip=1.12-1 \
            ca-certificates=20230311 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
