FROM debian:sid-20211011-slim

LABEL maintainer=<nic.cheneweth@thoughtworks.com>

# minimum packages required for use as a circleci remote-docker primary container
RUN apt-get update && \
    apt-get install --no-install-recommends -y \
            git=1:2.33.1-1 \
            openssh-server=1:8.7p1-1 \
            tar=1.34+dfsg-1 \
            gzip=1.10-4 \
            ca-certificates=20211016 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
