FROM alpine:3.15.0

LABEL maintainer=<nic.cheneweth@thoughtworks.com>

# minimum packages required for use as a circleci remote-docker primary container
RUN apk add --no-cache \
        git==2.34.1-r0 \
        openssh==8.8_p1-r1 \
        tar==1.34-r0 \
        gzip==1.11-r0 \
        ca-certificates==20191127-r7
