FROM alpine:3.17.0

LABEL maintainer=<nic.cheneweth@thoughtworks.com>

RUN apk add --no-cache \
        git==2.38.1-r0 \
        openssh==9.1_p1-r1 \
        tar==1.34-r1 \
        gzip==1.12-r0 \
        ca-certificates==20220614-r2
